version: "3.8"
services:
  ps_flask:
    build: .
    image: ps_flag:1.0
    restart: always
    container_name: "compose-ps"
    volumes:
      - "./:/app:rw"

    environment:
      - FLASK_DEBUG=product
    command:
      - /bin/sh
      - -c
      - |
            export FLASK_APP=app && gunicorn -t 30000 -w 4 -b flask run  0.0.0.0:8000 

    ports:
      - "99:8000"
    networks:
      - app_net

networks:
  app_net:
